package com.harshalit.controller;

import java.net.URI;
import java.security.Principal;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.security.authentication.AuthenticationManager;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.servlet.support.ServletUriComponentsBuilder;

import com.harshalit.entity.User;
import com.harshalit.entity.UserRequest;
import com.harshalit.entity.UserResponse;
import com.harshalit.service.UserService;
import com.harshalit.util.JWTUtil;

@RestController
@RequestMapping("/user")
public class UserRestController {

	@Autowired
	private UserService userService;

	@Autowired
	private JWTUtil util;

	@Autowired
	private AuthenticationManager authenticationManager;
	
	@PostMapping("/save")
	public ResponseEntity<String> registerUser(@RequestBody User user) {
		Integer id = userService.saveUser(user);
		return new ResponseEntity<>("Saved User with id "+id, HttpStatus.CREATED);
	}

	//validate user and generate token (login)
	@PostMapping("/login")
	public ResponseEntity<UserResponse> loginUser(@RequestBody UserRequest request){
		//validate username/pass with database
		authenticationManager.authenticate(
				new UsernamePasswordAuthenticationToken(
				request.getUserName(), 
				request.getPassword()));
		
		String token = util.generateToken(request.getUserName());
		return ResponseEntity.ok(new UserResponse(token,"Success! Generated by NIT"));
	}
	
	//3.after login only
	@GetMapping("/welcome")
	public ResponseEntity<String> accessData(Principal principal){
		return ResponseEntity.ok("Hello User......!"+principal.getName());
	}
	
}
